### ISSUE TITLE
README AND NPT FOUND ERROR ...

### ISSUE THREAD

**Issue by sepidll** [imec-idlab/IEEE-802.11ah-ns-3#10]
Hello, thanks for your contribution.

in the readme file, it is written :

### Installation and usage instructions ###
*...
* Change into ./802.11ah-ns3/ns-3 directory.  
* Build and run:
  ./waf --run "s1g-mac-test --seed=1 --simulationTime=60 --payloadSize=256 --Nsta=32 --NRawSta=32 --BeaconInterval=100000 --DataMode="OfdmRate7_8MbpsBW2MHz" --datarate=7.8  --bandWidth=2 --rho="50" --TrafficPath="./OptimalRawGroup/traffic/data-32-0.82.txt" --S1g1MfieldEnabled=false --RAWConfigFile="./OptimalRawGroup/RawConfig-32-2-2.txt" "

that it is so useful for me because i'm newborn to simulate with ns3, and this code passes all  parameters by cmd, but i faced error :

program 's1g-mac-test' not found; available programs are: ['test', 'scratch/test/test', 'RAW-generate', 'scratch/RAW-generate', 'scratch-simulator', 'scratch/scratch-simulator', 'rca', 'scratch/rca/rca', 'test-runner', 'utils/test-runner', 'bench-simulator', 'utils/bench-simulator', 'bench-packets', 'utils/bench-packets', 'print-introspected-doxygen', 'utils/print-introspected-doxygen', 'tap-device-creator', 'src/fd-net-device/tap-device-creator', 'raw-sock-creator', 'src/fd-net-device/raw-sock-creator', 'tap-creator', 'src/tap-bridge/tap-creator']

 before that i've just run, " CXXFLAGS="-std=c++11" ./waf configure --disable-examples --disable-tests " line code ... 

so it seems s1g-mac-test is not in files, what can i do now ?
Thanks for your attention

**Comment by ssi15004** [comment]
Good evening,

Sorry for this inconvenience, may I ask you to try to run instead:

• ./waf --run "test --seed=1 --simulationTime=60 --payloadSize=256 --Nsta=32 --NRawSta=32 --BeaconInterval=100000 --DataMode="OfdmRate7_8MbpsBW2MHz" --datarate=7.8 --bandWidth=2 --rho="50" --TrafficPath="./OptimalRawGroup/traffic/data-32-0.82.txt" --S1g1MfieldEnabled=false --RAWConfigFile="./OptimalRawGroup/RawConfig-32-2-2.txt” "

Thank you for your notification.

Kind regards,
Serena Santi

--
Serena Santi
PhD Researcher
at IDLab, University of Antwerp, in collaboration with imec
serena.santi@uantwerpen.be<mailto:serena.santi@uantwerpen.be>
The Beacon | Sint-Pietersvliet 7 | 2000 Antwerpen | Belgium

T: +32 3 265 88 11
M: +32 485 88 73 22
W: idlab.uantwerpen.be<http://idlab.uantwerpen.be>| idlab.technology<http://idlab.technology> | www.imec.be<http://idlab.technology>
T: @IDLabResearch<http://twitter.com/@IDLabResearch>

[https://idlab.uantwerpen.be/logos/uantwerp.png]       [https://idlab.uantwerpen.be/logos/imec.png]        [https://idlab.uantwerpen.be/logos/idlab.png]

On 28 Sep 2019, at 17:20, sepidll <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello, thanks for your contribution.

in the readme file, it is written :

Installation and usage instructions

*...

  *   Change into ./802.11ah-ns3/ns-3 directory.
  *   Build and run:
./waf --run "s1g-mac-test --seed=1 --simulationTime=60 --payloadSize=256 --Nsta=32 --NRawSta=32 --BeaconInterval=100000 --DataMode="OfdmRate7_8MbpsBW2MHz" --datarate=7.8 --bandWidth=2 --rho="50" --TrafficPath="./OptimalRawGroup/traffic/data-32-0.82.txt" --S1g1MfieldEnabled=false --RAWConfigFile="./OptimalRawGroup/RawConfig-32-2-2.txt" "

that it is so useful for me because i'm newborn to simulate with ns3, and this code passes all parameters by cmd, but i faced error :

program 's1g-mac-test' not found; available programs are: ['test', 'scratch/test/test', 'RAW-generate', 'scratch/RAW-generate', 'scratch-simulator', 'scratch/scratch-simulator', 'rca', 'scratch/rca/rca', 'test-runner', 'utils/test-runner', 'bench-simulator', 'utils/bench-simulator', 'bench-packets', 'utils/bench-packets', 'print-introspected-doxygen', 'utils/print-introspected-doxygen', 'tap-device-creator', 'src/fd-net-device/tap-device-creator', 'raw-sock-creator', 'src/fd-net-device/raw-sock-creator', 'tap-creator', 'src/tap-bridge/tap-creator']

before that i've just run, " CXXFLAGS="-std=c++11" ./waf configure --disable-examples --disable-tests " line code ...

so it seems s1g-mac-test is not in files, what can i do now ?
Thanks for your attention
