### ISSUE TITLE
Fast association mechanism

### ISSUE THREAD

**Issue by WasylPL** [imec-idlab/IEEE-802.11ah-ns-3#12]
Hi
I've read in the documentation that in the simulator has been implemented fast association mechanism but I cannot find any example of using it explicit in code. I'd like to conduct behavior of that and I will be grateful if you indicate where that mechanism is used.

**Comment by asljivo1** [comment]
Hi

First of all, I apologise for the delayed answer.

If you want to see the code implementing fast association, see StaWifiMac::SendAssociationRequest and ApWifiMac::SendOneBeacon lines 1180-1194. Every station generates a random value in StaWifiMac constructor and stores it in assocVaule. This random value is compared to fastAssocThreshold in StaWifiMac::SendAssociationRequest. Only the stations with the random value smaller than the threshold are allowed to send association request, whereas the rest need to delay their association attempt for m_assocRequestTimeout. This prevents a burst or many association requests at the same time. AP adjusts this threshold (AuthenThreshold) dynamically (in every beacon) based on its sending queue size. This results in increasing the threshold by 50 when the queue is smaller than 10, otherwise decreasing the threshold by 50. This threshold adaptarion mechanism is proposed in [1].

[1] H. Wang. Supporting Authentication/Association for Large Number of Stations, 2012., 2012. https://mentor.ieee.org/802.11/dcn/12/11-12-0112-04-00ah-supporting-of-the-authentication-association-forlarge-number-of-stations.pptx
