### ISSUE TITLE
assert failed. cond="m_pageSlice.GetPageindex() == m_TIM.GetPageIndex()"

### ISSUE THREAD

**Issue by CaesarGo** [imec-idlab/IEEE-802.11ah-ns-3#6]
Hello,

Thanks for your contribution. When I ran the "test" program, it showed this error.

_assert failed. cond="m_pageSlice.GetPageindex() == m_TIM.GetPageIndex()", file=../src/wifi/model/sta-wifi-mac.cc, line=407_

I looked up this in the source code (sta-wifi-mac.cc line 407), the assertion is triggered when the TIM element length is not correct. But I don't know how to solve this problem. 

Thanks in advance for your help!

**Comment by asljivo1** [comment]
Hello,

We cannot reproduce this error. We cannot precisely debug the program without the error, but we can try to help you with debugging. 

Try adding line m_TIM.SetPageIndex (m_PageIndex); just before beacon.SetTIM (m_TIM); in ApWifiMac. Does it make any difference?

I suspect the problem is that page index is uninitialized somewhere, and my compiler initializes it with 0 (accidentally the correct value), whereas yours doesn't. It can happen either for m_pageSlice or m_TIM (both should equal zero in the test simulation). In scratch/test/s1g-test-tim-raw.cc in functions configurePageSlice() and configureTIM() page index is set to 0 (setting for <=2048 stations where tim offset = 0). Please make sure they are set to 0 in your code. These configurations are passed to ApWifiMac through ns-3 attributes TIMSet and PageSliceSet and stored in attributes m_TIM and m_pageslice respectively. ApWifiMac manipulates with m_TIM and m_pageslice and encodes them into beacons. TIM element and page slice element are serialized in src/wifi/model/tim.cc and  src/wifi/model/pageSlice.cc, so print out the serialized value and the deserialized value of page index in pageSlice::SerializeInformationField, pageSlice::DeserializeInformationField, TIM::SerializeInformationField and TIM::DeserializeInformationField. What are the printed values? At least one has to be different from 0. From here we will know where to look for the bug further.

How did you determine that the TIM element length is not correct? If TIM element's length is >2, that means that the TIM element carries a non-empty partial virtual bitmap (indicating downlink data). This does not mean that the TIM length is incorrect. 

Workaround: you can comment line 407, I believe the program will still work correctly.

**Comment by CaesarGo** [comment]
Thanks for your reply.

I have commented this line, and the program worked.

Thanks a lot!
