### ISSUE TITLE
RCA example

### ISSUE THREAD

**Issue by vioxx1992** [imec-idlab/IEEE-802.11ah-ns-3#8]
I just install ns-3 802.11ah, and try the example: ./waf --run "rca --seed=1 --simulationTime=60 --payloadSize=256", but the following error occurred:

Checking RAW and TIM configuration... assert failed. cond="config.pageSliceCount == config.rps.rpsset.size()", file=../scratch/rca/s1g-rca.cc, line=258 terminate called without an active exception Command ['/home/vioxx/IEEE-802.11ah-ns-3/build/scratch/rca/rca', '--seed=1', '--simulationTime=60', '--payloadSize=256'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>").

There are some extra configuration to do?

**Comment by soczysty7** [comment]
Hi vioxx1992 here is the stack trace from insight debugger :

![image](https://user-images.githubusercontent.com/25151031/57016539-efd25800-6c1a-11e9-8d22-a3df5c1a40d6.png)

btw:[ here is the tutorial to install insight ](http://www.dalfonso.co/2016/04/23/setting-insight-debugger-on-ubuntu-16-04-lts/)
run it with: ./waf --run rca --command-template="insight %s"

As you can see the function **checkRawAndTimConfiguration ()** reports a problem because there is a mismatch between RAW&TIM config fetched from default _Configuration.h_. As developers mentioned 
 
> Note: RAW configuration must be in line with TIM and page configuration. If a RAW group is reserved 
> for a station in beacon interval that does not correspond to its TIM, station will be asleep during that RAW.

You can fix this by 
1 commenting this call //checkRawAndTimConfiguration (); (as it is done in 'test' scenario although it works there)
2 Correcting the config in _Configuration.h_ / tuning it to your research needs, for example using the special config 

> To configure a single page slice (whole page encoded in a single page slice)

```
uint32_t pageSliceLength=1; //  Number of blocks in each TIM for the associated page except for the last TIM (1-31) (value 0 is reserved);
uint32_t pageSliceCount=0;  //  Number of TIMs in a single page period (1-31)
```
Best Regards,
Michał
